name: devops

services:
  # BUCKETS
  minio-single:
    image: 'minio/minio:RELEASE.2024-12-18T13-15-44Z'
    container_name: 'minio-single'
    command: 'server --console-address ":9001"'
    environment:
      MINIO_CONFIG_ENV_FILE: '/etc/config.env'
      MINIO_BROWSER_REDIRECT_URL: 'http://minio-webui.docker.localhost'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.minio-webui.rule=Host(`minio-webui.docker.localhost`)'
      - 'traefik.http.routers.minio-webui.entrypoints=web'
      - 'traefik.http.routers.minio-webui.service=minio-webui'
      - 'traefik.http.services.minio-webui.loadbalancer.server.port=9001'
      - 'traefik.http.routers.minio.rule=Host(`s3.docker.localhost`)'
      - 'traefik.http.routers.minio.entrypoints=web'
      - 'traefik.http.routers.minio.service=minio'
      - 'traefik.http.services.minio.loadbalancer.server.port=9000'
    volumes:
      - './configurations/minio-single/config.env:/etc/config.env:ro'
      - 'minio_single_data:/mnt/data'
    networks:
      kestra_ministack:
        ipv4_address: '10.1.0.54'
  # DATABASES for kestra clients
  kestra-postgres:
    image: 'postgres:16.6-alpine3.21'
    container_name: 'kestra-postgres'
    environment:
      POSTGRES_DB: 'kestra'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'changeme'
    volumes:
      - 'kestra_postgres_data:/var/lib/postgresql/data'
    networks:
      kestra_ministack:
        ipv4_address: '10.1.0.55'
  kestra-pgadmin:
    image: 'dpage/pgadmin4:8.14.0'
    container_name: 'pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@localhost.com'
      PGADMIN_DEFAULT_PASSWORD: 'changeme'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.docker.localhost`)'
      - 'traefik.http.routers.pgadmin.entrypoints=web'
      - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
    volumes:
      - 'kestra_pgadmin_data:/var/lib/pgadmin'
    networks:
      kestra_ministack: {}
  # KEYCLOAK
  keycloak:
    depends_on:
      - 'keycloak-postgres'
    image: 'quay.io/keycloak/keycloak:26.0.7'
    container_name: 'keycloak'
    environment:
      KC_DB: 'postgres'
      KC_DB_URL: 'jdbc:postgresql://keycloak-postgres:5432/keycloak'
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'changeme'
      KC_HOSTNAME: 'keycloak.docker.localhost'
      KC_HOSTNAME_PORT: '8080'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_LOG_LEVEL: 'info'
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'changeme'
    command:
      - 'start-dev'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.keycloak.rule=Host(`keycloak.docker.localhost`)'
      - 'traefik.http.routers.keycloak.entrypoints=web'
      - 'traefik.http.services.keycloak.loadbalancer.server.port=8080'
    networks:
      kestra_ministack: {}
  keycloak-postgres:
    image: 'postgres:16.6-alpine3.21'
    container_name: 'keycloak-postgres'
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'changeme'
    volumes:
      - 'keycloak_postgres_data:/var/lib/postgresql/data'
    networks:
      kestra_ministack: {}

volumes:
  minio_single_data: {}
  kestra_postgres_data: {}
  kestra_pgadmin_data: {}
  keycloak_postgres_data: {}

networks:
  kestra_ministack:
    external: true
