services:
  kestra-client-1:
    image: 'ghcr.io/gperreymond/hashibase:base-1.0.0'
    container_name: 'kestra-client-1'
    hostname: 'kestra-client-1'
    privileged: 'true'
    post_start:
      - command: 'start-ministack'
    pre_stop:
      - command: 'service nomad stop'
    environment:
      MINISTACK: 'true'
      NOMAD_VERSION: '1.9.5'
    volumes:
      - '/tmp/ministack/configurations/nomad/config.hcl:/nomad/config/config.hcl'
      - '/tmp/ministack/configurations/nomad/base.hcl:/etc/nomad.d/config/00-base.hcl'
      - '/tmp/ministack/configurations/nomad/client.hcl:/etc/nomad.d/config/00-client.hcl'
      - '$HOME/.ministack/kestra/nomad/client.hcl:/etc/nomad.d/config/01-client.hcl'
      - '$HOME/.ministack/kestra/nomad/certs:/certs'
      - 'nomad_client_kestra-client-1_data:/nomad/data'
    networks:
      ministack:
        ipv4_address: '10.1.0.21'

volumes:
  nomad_client_kestra-client-1_data: {}

networks:
  kestra_ministack:
    external: true
