scrape_configs:
  - job_name: 'kestra-clients'
    nomad_sd_configs:
      - server: 'https://nomad-server-1:4646'
        namespace: 'kestra-client-1'
        tls_config:
          insecure_skip_verify: true
      - server: 'https://nomad-server-1:4646'
        namespace: 'kestra-client-2'
        tls_config:
          insecure_skip_verify: true
      - server: 'https://nomad-server-1:4646'
        namespace: 'kestra-client-3'
        tls_config:
          insecure_skip_verify: true
    relabel_configs:
      - source_labels: ['__meta_nomad_tags']
        regex: '.*,prometheus\/scrape=true(.*?),.*'
        action: keep
      - source_labels: ['__metrics_path__']
        regex: '(.*)'
        target_label: '__metrics_path__'
        replacement: '/prometheus'
      - source_labels: ['__meta_nomad_namespace']
        regex: '(.*)'
        target_label: 'nomad_namespace'
        replacement: '$1'
