name: netbird
services:
  # Caddy reverse proxy
  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.netbird.rule=Host(`netbird.docker.localhost`)"
      - 'traefik.http.routers.netbird.entrypoints=web'
    networks:
      kestra_ministack:
        ipv4_address: '10.1.0.77'
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # UI dashboard
  dashboard:
    image: netbirdio/dashboard:v2.9.0
    restart: unless-stopped
    networks:
      kestra_ministack: {}
    env_file:
      - ./dashboard.env
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Signal
  signal:
    image: netbirdio/signal:0.36.3
    restart: unless-stopped
    networks:
      kestra_ministack: {}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Relay
  relay:
    image: netbirdio/relay:0.36.3
    restart: unless-stopped
    networks:
      kestra_ministack: {}
    env_file:
      - ./relay.env
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Management
  management:
    image: netbirdio/management:0.36.3
    restart: unless-stopped
    extra_hosts:
      - "netbird.docker.localhost:10.1.0.77"
    networks:
      kestra_ministack: {}
    volumes:
      - management_data:/var/lib/netbird
      - ./management.json:/etc/netbird/management.json
    command: [
      "--port", "80",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.selfhosted",
      "--dns-domain=netbird.selfhosted",
      "--idp-sign-key-refresh-enabled",
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Coturn, AKA relay server
  coturn:
    image: coturn/coturn:edge-debian
    restart: unless-stopped
    #domainname: netbird.relay.selfhosted
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    network_mode: host
    command:
      - -c /etc/turnserver.conf
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Zitadel - identity provider
  zitadel:
    restart: 'always'
    networks:
      kestra_ministack: {}
    image: 'ghcr.io/zitadel/zitadel:v2.64.1'
    command: 'start-from-init --masterkeyFromEnv --tlsMode disabled'
    env_file:
      - ./zitadel.env
    depends_on:
      zdb:
        condition: 'service_healthy'
    volumes:
      - ./machinekey:/machinekey
      - zitadel_certs:/zdb-certs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
  # Postgres for Zitadel
  zdb:
    restart: 'always'
    networks:
      kestra_ministack: {}
    image: 'postgres:16-alpine'
    env_file:
      - ./zdb.env
    volumes:
      - zdb_data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
volumes:
  zdb_data:
  management_data:
  caddy_data:
  zitadel_certs:

networks:
  kestra_ministack:
    external: true
